# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36c1d8b3776c609f31b6c1a7a5f03bda05f27707b05efd26abd919d4b8b48496e2801287e021c7aed12a242b5b06cb0aaa4c380cec5e50272efa5fafc7bcee11

test:
  secret_key_base: b05d77e8dcd28124f93ddb2350f98ba8034cc0531d4c24685658263d441043ec9ec652fe339f1f367f69a4346a8065717c52a728a20f814dff4ed87190fa62b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
